### ISSUE TITLE
JSON-B and JSON-P API dependencies should have 'provided' scope

### ISSUE THREAD

**Issue by hwellmann** [eclipse-ee4j/yasson#193]
## Scenario

Working in a Java EE context with Maven, you normally have a provided scope dependency on javax:javaee-api.

To use any implementation specific API of Yasson (like YassonProperties), you need to add a compile scope or provided scope dependency on org.eclipse:yasson.

As a consequence, you get compile or provided scope transitive dependencies on javax.json:javax.json-api and javax.json.bind:javax.json.bind-api.

This causes
* duplicate packages on the compile time classpath
* duplicate type errors (at least in Eclipse with Java 11)
* inclusion of the JSON-P and JSON-B API JARs in your WAR when using Yasson with compile scope

## Goal

Yasson should use **provided** scope for the javax.json:javax.json-api and javax.json.bind:javax.json.bind-api dependencies.

## Workaround

Users of Yassons must add the following to their POM:

            <dependency>
                <groupId>org.eclipse</groupId>
                <artifactId>yasson</artifactId>
                <version>1.0.2</version>
                <exclusions>
                    <exclusion>
                        <groupId>javax.json</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>javax.json.bind</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

**Comment by aguibert** [comment]
Using a provided scope may be better for your use case, but remember that Yasson is also usable outside of a JavaEE context, and it should continue to be usable in this way.

The dominant use-cases are:
- JavaSE env: Pull in yasson as a dependency (drags in API automatically too, which is good)
- JavaEE env: Using just JSON-B spec, no vendor-specific APIs.  Here the app server provides API and and impl

I think using Yasson-specific APIs in a JavaEE env are not a majority case in the overall usage pattern, and since we cannot satisfy all use cases I still side with leaving the API dependencies how they are (compile scope).

Note that if you use Gradle instead of Maven, they have an easy mechanism where you can simply [turn off transitive dependenceis](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sub:disabling_resolution_transitive_dependencies).

**Comment by oliviercailloux** [comment]
If you set yasson with provided scope, its dependencies in turn automatically become provided from the point of view of your project, according to the official [doc](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html). It seems to me that things are correctly set up in yasson’s own pom, thus. Maybe there’s a problem somewhere else with some tool not respecting provided scope semantics.

**Comment by aguibert** [comment]
you're right @oliviercailloux, he did say "compile scope or provided scope dependency on org.eclipse:yasson" in the OP, but based on the code example I'm guessing he meant "compile" scope.

So the scenario he seems to care about is compile scope on Yasson, but provided scope on everything else.

In any case, in order to make this change the usage pattern of Yasson=compile everythingElse=provided would need to be a dominant use case (e.g. >80%) and clearly it's not, so I'm going to close out this issue.
