### ISSUE TITLE
Publish SNAPSHOTs, or document their locations

### ISSUE THREAD

**Issue by oliviercailloux** [eclipse-ee4j/yasson#204]
Are yasson SNAPSHOTs published to some Maven repository? I can’t find information about this.

The [parent pom](https://github.com/eclipse-ee4j/ee4j/blob/master/parent/pom.xml) references the Sonatype Nexus Staging [repository](https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/), but I can’t find recent yasson artifacts there.

I also found (outdated?) information related to an eclipse specific [repository](https://repo.eclipse.org/content/repositories/), but nothing recent there either apparently.

**Comment by aguibert** [comment]
@bravehorsie @m0mus I'm having trouble finding this information too.

Looks like the Yasson CI/CD pipeline is here: https://ci.eclipse.org/yasson/

According to build logs, there are a few different repos:
- https://repo.eclipse.org/content/repositories/yasson/org/eclipse/yasson/
- https://repo.eclipse.org/content/repositories/yasson-releases/org/eclipse/yasson/
- https://repo.eclipse.org/content/repositories/yasson-snapshots/org/eclipse/yasson/

I think the "yasson-snapshots" repo is the correct one, as it has the newest snapshot, 1.0.2-SNAPSHOT.

Looks like there is no 1.0.3-SNAPSHOT yet, perhaps because there has been no green build since this change? https://github.com/eclipse-ee4j/yasson/commit/77580b27411bdac5e37fe38285a194786224a240

Also, I see Yasson has a Travis CI build here (which is green): https://travis-ci.org/eclipse-ee4j/yasson
However, the Travis build is just building the project and running tests.  It's not publishing releases/snapshots anywhere.

So it seems Travis it working and Jenkins is broken.  Are both needed?  Having some information about this in the README would be helpful.

**Comment by bravehorsie** [comment]
I don't think we do publish snapshots. We may need to create a job for it.

**Comment by aguibert** [comment]
@bravehorsie We seem to have a snapshot repo and pipeline setup, which is working completely except for the very last step where it tries to upload the snapshot artifact to the snapshot repo.  See issue #206 for details.  I'm hoping you or some of your other Oracle co-workers that set up the pipeline could clarify the original intent of this pipeline and whether or not it should still be working going forward to JakartaEE.

**Comment by oliviercailloux** [comment]
Would perhaps someone consider publishing manually a 1.0.3-SNAPSHOT version, in the meantime, if it’s not difficult? I would be happy to benefit from a few recent patches.

**Comment by bravehorsie** [comment]
Snapshot version for Yasson has been published.
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/yasson/1.0.3-SNAPSHOT/

**Comment by bravehorsie** [comment]
The build is configured to poll SCM changes and republish new version when available.

**Comment by oliviercailloux** [comment]
Shouldn’t the current SNAPSHOT be named `1.0.4`? `1.0.3` is [out](https://search.maven.org/search?q=g:org.eclipse%20AND%20a:yasson&core=gav) already.

**Comment by aguibert** [comment]
yes it should. Looks like we just forgot to bump the version after cutting 1.0.3. I've created+merged https://github.com/eclipse-ee4j/yasson/pull/268 which bumps up to 104-snapshot
