### ISSUE TITLE
@JsonbProperty on setter is broken 1.0.5

### ISSUE THREAD

**Issue by tsfullman** [eclipse-ee4j/yasson#355]
After updating from 1.0.4 to 1.0.5, my unit test breaks which now deserializes my 2d array to null every time. It previously deserialized correctly with 1.0.4 and passed the test.  It only doesn't work when there is a custom deserializer associated with the class.

I am deserializing to an interface which my class implements. The interface has the custom deserializer annotated on it for multiple types.

**Comment by aguibert** [comment]
hi @tsfullman, thanks for reporting this issue. Are you able to provide a test case to reproduce the issue?

**Comment by aguibert** [comment]
Looking through the changes I believe this PR may have been related: https://github.com/eclipse-ee4j/yasson/pull/271 to the behavior change

**Comment by Degubi** [comment]
The bug started happening after #288, if I revert 'propertyModel.getPropertyName()' to 'propertyModel.getReadName()' the test passes again.

**Comment by Degubi** [comment]
Printing out the names it looks like the annotation is getting ignored somewhere:
PROPNAME: test
READNAME: apple

**Comment by aguibert** [comment]
thanks for the investigation @Degubi, it looks like you are on the right track. Are you going to continue investigating this one? Just want to make sure we don't duplicate work

**Comment by Degubi** [comment]
Yes I do @aguibert, I was just waiting for some feedback before continuing.

**Comment by Degubi** [comment]
Actually I don't think I have the right idea to fix this @aguibert. I was poking around in ClassParser::toPropertyMethod, I found that this is the method that creates the names used in Property.java. I thought that the problem was that the check was missing for the JsonbProperty annotation (in ClassParser::toPropertyMethod), but then other tests broke when I put in the annotation handling code... so had to put in more checks to see if the class has a declared private field as the value of the JsonbProperty annotation. Now the broken and all the original tests pass, but I don't think this is the right solution... just seems wrong to me.

**Comment by aguibert** [comment]
I think you were sort of on the right track @Degubi, the main issue is that we had 2 separate PropertyModel instances for the class when we should only have had one. In PR #357 I added some extra code to process the PropertyModel list for a class and merge duplicate PropertyModels as needed. I'm considering two PropertyModels duplicate if their readName and writeName attributes are equal.

**Comment by onacit** [comment]
Is it (or am I) normal when I see this problem with `3.0.3`?
