### ISSUE TITLE
PrivateFieldsStrategy uses reflection?

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#382]
I have a question:

If I use this:
```

public final class PrivateFieldsStrategy implements PropertyVisibilityStrategy {

	@Override
	public boolean isVisible(Field field) {
		return true;
	}

	@Override
	public boolean isVisible(Method method) {
		return false;
	}
}
```

and add it to a class:

```
@JsonbVisibility(value = PrivateFieldsStrategy.class)
public class User{

}
```

will yasson use reflection to access the private fields? If so, then does this mean that the default (method level access with getter) is faster for (de)serializing. Should I avoid `PrivateFieldsStrategy` in terms of performance?

**Comment by Degubi** [comment]
I don't think your PrivateFieldsStrategy should cause any problems performance wise.

PropertyValuePropagation.java line 123 checks if the field is made accessible by a PropertyVisibilityStrategy.
If yes, it calls setAccessible(true) on the field if it is private. Same goes for methods. (happens only once per field/method)
If the field/method was public it simply invokes it.

**Comment by nimo23** [comment]
>I don't think your PrivateFieldsStrategy should cause any problems performance wise.

but in compare to property access, the field access is made by _reflection_ . Or?

**Comment by aguibert** [comment]
All property access in any JSON library (Yasson, Jackson, etc) is made via reflection because the JSON libraries must programatically discover the properties of the class and invoke them. As @Degubi pointed out earlier there is an extra step with private field access where fields must be set accessible first, but this only happens once so the performance cost is negligible.
