### ISSUE TITLE
Big long numbers are not serialized as strings

### ISSUE THREAD

**Issue by MartijnDwars** [eclipse-ee4j/yasson#397]
**Describe the bug**
From the JSON-B specification:

> *3.16. Big numbers*
> JSON Binding implementation MUST serialize/deserialize numbers that express greater magnitude or precision than an IEEE 754 double precision number as strings.

The value `Long.MAX_VALUE - 1` cannot be precisely represented by a IEEE 754 double precision number, as the following jshell session shows:

```
jshell> var l = Long.MAX_VALUE - 1
l ==> 9223372036854775806

jshell> (long) (double) l
$29 ==> 9223372036854775807

jshell> (long) (double) l == l
$30 ==> false
```

Therefore, this value should be serialized as the JSON string `"9223372036854775806"`. However, with Yasson we get the following:

```
jshell> import javax.json.bind.JsonbBuilder

jshell> var jsonb = JsonbBuilder.create();
jsonb ==> org.eclipse.yasson.internal.JsonBinding@2d127a61

jshell> class Container<T> {
   ...>   public T instance;
   ...>   public Container() {
   ...>   }
   ...> }
|  created class Container

jshell> long l = Long.MAX_VALUE - 1;
l ==> 9223372036854775806

jshell> var container = new Container<>();
container ==> Container@65466a6a

jshell> container.instance = l;
$7 ==> 9223372036854775806

jshell> jsonb.toJson(container);
$8 ==> "{\"instance\":9223372036854775806}"
```

Note that the value is serialized as a JSON number, not as a JSON string. The risk of course is that if you feed this to a JavaScript engine, the numbers will get messed up:

```
> var x = {"instance":9223372036854775806}
undefined
> x.instance
9223372036854776000
```

**To Reproduce**
See above.

**Expected behavior**
The expected result when calling `toJson(container)` in the example above is:

```
$8 ==> "{\"instance\":\"9223372036854775806\"}"
```

**System information:**
 - OS: macOS 10.14.6
 - Java Version: 8, 11
 - Yasson Version: 1.0.6

**Comment by aguibert** [comment]
Hi @MartijnDwars, thanks for raising this issue. This is the result of a bug in the JSON-B 1.0 spec that needs to be revised in the next version. It has been debated at the spec level under https://github.com/eclipse-ee4j/jsonb-api/issues/82 and https://github.com/eclipse-ee4j/jsonb-api/issues/112, but ultimately Yasson 1.0.X is doing the correct thing for now and we will fix it in 2.0 when we can revise the spec.

The main reason we had to change Yasson in this way is that we found out other components weren't able to cope with values being numbers sometimes and strings at other times, particularly in schema-based designs as described in jsonb-api#112.

I'm going to close this issue because we need to address it at the JSON-B spec level.
