### ISSUE TITLE
Record with no-arg constructor with does not deserialise correctly

### ISSUE THREAD

**Issue by dansiviter** [eclipse-ee4j/yasson#549]
**Describe the bug**
If a record has a no-arg constructor when deserialised the optional is always `<empty>`. 

**To Reproduce**
An example is available [here](//gist.github.com/dansiviter/9d826225a553a3b5e493bac944fca7ce).

**Expected behavior**
The correct constructor for the record is selected.

**System information:**
 - OS: Windows 11
 - Java Version: 17
 - Yasson Version: 3.0.0-RC1

**Additional context**
N/A

**Comment by dansiviter** [comment]
Updates as I originally thought it was due to `Optional` but appears it happens every time.

**Comment by Verdent** [comment]
Hi Dan, this is happening due to default empty constructor you are having in all of the records. Yasson is trying to find `@JsonbCreator` annotated constructor/factory and finds none, but since it does have default constructor, if  backs to use that. If you remove empty constructor, everything will work as expected. Or if you need that default constructor for some reason, you can overwrite the parametrized one and mark it as `@JsonbCreator` and Yasson. This is possible workaround for now.

Now I am thinking whether we should throw an exception in cases when record do have multiple constructors (including the default one) and none of them is marked as `@JsonbCreator`. It might possibly make sense for records.

**Comment by dansiviter** [comment]
From [RecordTest.java:L69](/eclipse-ee4j/yasson/blob/master/src/test/java16/org/eclipse/yasson/records/RecordTest.java#L69) it does suggest that it should throw an exception but I'm not seeing that behaviour in 3.0.0-RC1. 🤔

**Comment by dansiviter** [comment]
I've just checked and it's due to default no-args constructor behaviour of records. I'd argue a no-arg constructor is a pointless record so should throw an exception regardless.

**Comment by Verdent** [comment]
Exactly my thought when I was analyzing it yesterday. I will make the needed change :-)

**Comment by Verdent** [comment]
It does fail for multiple constructors, but since it is taking nearly the same processing path as regular class, I forgot to make it to fail when default constructor is present.
